version: '3.5'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: shorten
      POSTGRES_PASSWORD: shorten
      POSTGRES_DB: shorten
    expose:
      - 5432

  shorten:
    build: .
    image: shorten
    environment:
      DB_USERNAME: shorten
      DB_HOST: db
      DB_PASSWORD: shorten
      DB_NAME: shorten
      BASE_URL: http://shorten:8000
    expose:
      - 8000
    depends_on:
      - db

  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    entrypoint: ./wait-for-it.sh -t 5 shorten:8000 -- npm run test
    environment:
      APP_URL: http://shorten:8000
    depends_on:
      - db
      - shorten
