FROM node:14.8-alpine AS build

WORKDIR /usr/src/app

RUN apk add bash wget && wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

COPY package*.json ./
COPY tsconfig.json .
COPY jest.config.js .
COPY src ./src

RUN npm install

ENTRYPOINT ["npm", "run", "test"]
